README.md
Add a link to the minor planets center
=> Add Minor Planet Center

README.md
Hey fellows! Super cool list. If you deem it worthy, I would like to add my own project, [Harmony of the Spheres](https://thehappykoala.github.io/Harmony-of-the-Spheres/#/scenario/The%20Sun%20and%20the%20Neptunian%20System), to the list of interactive planetariums. It's very much a living project and new contributors are always welcome, regardless of their skill level 🚀 🚀 🚀 
Was not sure whether I should add a link to the repository or the website where you can use Harmony of the Spheres, but I went for the repository to make it easier for folks that might want to contribute to find where they can do so! 
Happy Saturday!
=> Add Harmony of the Spheres to the list of interactive planetariums

README.md
=> Add Orb Viewer and Orb Calc

README.md
Added Sourceforge download link to NASA's GMAT
=> Added GMAT

README.md
Added link to NASA's Solar System Treks webpage
=> Added NASA's Solar System Treks

README.md
Thanks for this list!  I've added a couple of links for projects I maintain.
Cheers,
Bill
=> Added "Predict" and "Where the ISS At?" links

README.md
=> Add Perl library for SGP4/8 propagation

README.md
Adds Rebound, a sophisticated N-body integrator.
=> Add Rebound

README.md
Adds a listing for KStars which addresses issue #20.
=> Add KStars

README.md
Adds a link to the NASA sub-page on data.gov along with a hint for finding additional space-related datasets on that portal
=> Add Data.gov

README.md
Hello again,
just moving on with my "community" proposals :)
this time with NASA data to support education of the coming generations
=> Add NITARP data & projects listing

README.md
Hello again,
just moving on with my "community" proposals :)
=> Add section challenges and hackathons

README.md
Hello again,
just moving on with my "community" proposals :)
this time I'm actually proposing to rename the "other" section to "community" and moving its content to more specific sections.
=> Reorganize the section "other"

README.md
Add [Spacekit](https://typpo.github.io/spacekit/), an open-source JS library for building space visualizations.
=> Add Spacekit.js

README.md
Disclaimer: I'm one of the maintainer of this project!
=> Add Open Space Toolkit

README.md
Hello!
I'd like to add FreeFlyer to the "Mission Design" section. Here's a [video](https://www.youtube.com/watch?v=Cwau4GrxuUU) that demonstrates they types of analysis FreeFlyer supports.
Thanks!
=> Add FreeFlyer

README.md
Added the Space Launch Report (https://www.spacelaunchreport.com/)
=> Added Space Launch Report

README.md
Also broke out a few more subcategories in hardware, and added a Simulation category (separate from mission design).
=> Added several packages

README.md
Sorry, I noticed the formatting was wrong due to an extra space
=> Update Yamcs link

README.md
Adding two resources submitted by Tom Johnson, SVP Innovation @ [Analytical Graphics, Inc.](HTTP://agi.com) This is a for-profit company and these are paid. I don't think we denote that for other resources. LMK what you think.
=> Adding AGI resources

README.md
100,000 Stars is an interactive visualization of the stellar neighborhood showing the location of 119,617 nearby stars.
=> Add 100,000 Stars

README.md
See [here](https://github.com/chrismolli/ProjectInertia). It is currently only a prototype but I put all the hw files and firmware crates.
=> Added open source hw project

README.md
fixing https://github.com/orbitalindex/awesome-space/issues/57
=> Added space engine

README.md
Added Orbiter 2016 ( here's how it looks - https://www.youtube.com/results?search_query=scott+manley+orbiter+2016 )
Installing it is quite challenging, so also added a link to a reddit post which has detailed instructions.
=> Orbiter 2016

README.md
Adding a link to [perturb](https://github.com/gunvirranu/perturb)
=> Add the perturb library for C++ SGP4 orbit prediction

README.md
1. Added link to space jargon cheatsheet
2. Added link to LunCo sim
=> - Added a few links

README.md
Go by ienai SPACE is a free software tool for mission analysis using electric propulsion.
=> Adding "GO by ienai SPACE"

README.md
Adding Mars Now - explorer visualizes current locations and status of orbiters and rovers.
=> Add Mars Now explorer

README.md
Adding an entry for the pretrained model Python library Moonshine
=> Update README with Moonshine for remote sensing ML

README.md
Open-Source TypeScript library for working with TLEs/Satellites.
=> Add Orbital Object Toolkit

README.md
This comprehensive guide is tailored to meet the needs of space industry startups. It covers multiple topics such as licensing of space activities, public-private partnerships in space, legal intricacies of launching payloads, and space risk insurance.
=> Added NewSpace Startup Legal Guide

README.md
I've removed smd since I'm the author, and it's been unmaintained since 2017. Nyx is its successor.
=> Update Nyx, add ANISE, remove smd

README.md
The Space Launch Report website is now some SEO squatting app website.
=> remove dead site from README.md

README.md
- Add SUCHAI-2 complete satellite flight software and ground software
- Add SUCHAI FS flight software framework
=> Add University of Chile's SUCHAI missions software

README.md
I would like to propose adding [www.satcat.com](www.satcat.com) on this list. It is a web application that is powered by a unified database that is populated with popular sources of free data (Space-track, Jonathan McDowell's GCAT, NOAA SWPC, etc). It also includes tools such as a TLE parser, time conversion tools, a orbit propagation sandbox, and an orbit designer.
Thank you!
=> Adding a new service

README.md
=> added copernicus and otis
